# Generated by Django 3.2.13 on 2025-03-16 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('soft drink', 'Soft Drink'), ('alcoholic', 'Alcoholic'), ('non-alcoholic', 'Non-Alcoholic'), ('hot drink', 'Hot Drink'), ('shot', 'Shot'), ('punch', 'Punch'), ('cocktail', 'Cocktail'), ('beer', 'Beer'), ('wine', 'Wine'), ('champagne', 'Champagne'), ('liqueur', 'Liqueur'), ('other', 'Other')], max_length=50)),
                ('instruction', models.TextField()),
                ('glass', models.CharField(choices=[('highball', 'Highball'), ('whiskey', 'Whiskey'), ('martini', 'Martini'), ('margarita', 'Margarita'), ('collins', 'Collins'), ('pint', 'Pint'), ('champagne', 'Champagne'), ('shot', 'Shot'), ('punch', 'Punch'), ('beer', 'Beer'), ('wine', 'Wine'), ('cocktail', 'Cocktail'), ('other', 'Other')], max_length=50)),
                ('alcoholic', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('alcoholic', models.BooleanField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CocktailIngredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('cocktail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cocktails.cocktail')),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cocktails.ingredient')),
            ],
        ),
    ]
