# Generated by Django 3.2.13 on 2025-03-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='type',
            field=models.CharField(choices=[('vodka', 'Vodka'), ('rum', 'Rum'), ('whiskey', 'Whiskey'), ('gin', 'Gin'), ('tequila', 'Tequila'), ('brandy', 'Brandy'), ('liqueur', 'Liqueur'), ('wine', 'Wine'), ('beer', 'Beer'), ('champagne', 'Champagne'), ('soda', 'Soda'), ('juice', 'Juice'), ('syrup', 'Syrup'), ('cola', 'Cola'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
