# Generated by Django 3.2.13 on 2025-03-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0002_ingredient_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktailingredient',
            name='cocktail',
        ),
        migrations.AddField(
            model_name='cocktail',
            name='cocktail_ingredients',
            field=models.ManyToManyField(related_name='cocktail_ingredients', to='cocktails.CocktailIngredient'),
        ),
    ]
