# Generated by Django 3.2.13 on 2025-03-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0003_auto_20250316_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktailingredient',
            name='amount',
            field=models.CharField(choices=[('ml', 'ml'), ('cl', 'cl'), ('oz', 'oz'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('dash', 'dash'), ('piece', 'piece'), ('slice', 'slice'), ('wedge', 'wedge'), ('leaf', 'leaf'), ('pinch', 'pinch'), ('drop', 'drop'), ('cup', 'cup'), ('shot', 'shot'), ('bottle', 'bottle'), ('can', 'can'), ('bunch', 'bunch'), ('bottle', 'bottle'), ('other', 'other')], default='ml', max_length=50),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='alcoholic',
            field=models.BooleanField(default=True),
        ),
    ]
