# Generated by Django 3.2.13 on 2025-03-16 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0004_auto_20250316_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktailingredient',
            name='amount',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cocktailingredient',
            name='ingredient',
            field=models.OneToOneField(choices=[('ml', 'ml'), ('cl', 'cl'), ('oz', 'oz'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('dash', 'dash'), ('piece', 'piece'), ('slice', 'slice'), ('wedge', 'wedge'), ('leaf', 'leaf'), ('pinch', 'pinch'), ('drop', 'drop'), ('cup', 'cup'), ('shot', 'shot'), ('bottle', 'bottle'), ('can', 'can'), ('bunch', 'bunch'), ('bottle', 'bottle'), ('other', 'other')], default='ml', on_delete=django.db.models.deletion.CASCADE, to='cocktails.ingredient'),
        ),
    ]
