# Generated by Django 5.1.7 on 2025-03-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0006_auto_20250316_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='alcoholic',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='category',
            field=models.CharField(choices=[('soft drink', 'Soft Drink'), ('sweet', 'Sweet'), ('sour', 'Sour'), ('dry', 'Dry'), ('bitter', 'Bitter'), ('strong', 'Strong'), ('sparkling', 'Sparkling'), ('creamy', 'Creamy'), ('fruity', 'Fruity'), ('spicy', 'Spicy'), ('hot', 'Hot'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='type',
            field=models.CharField(choices=[('vodka', 'Vodka'), ('rum', 'Rum'), ('whiskey', 'Whiskey'), ('gin', 'Gin'), ('tequila', 'Tequila'), ('brandy', 'Brandy'), ('liqueur', 'Liqueur'), ('wine', 'Wine'), ('beer', 'Beer'), ('champagne', 'Champagne'), ('soda', 'Soda'), ('juice', 'Juice'), ('syrup', 'Syrup'), ('cola', 'Cola'), ('coffee', 'Coffee'), ('milk', 'Milk'), ('cream', 'Cream'), ('egg', 'Egg'), ('fruit', 'Fruit'), ('herb', 'Herb'), ('spice', 'Spice'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
