# Generated by Django 5.1.7 on 2025-03-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0007_alter_cocktail_alcoholic_alter_cocktail_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='category',
            field=models.CharField(choices=[('soft drink', 'Soft Drink'), ('sweet', 'Sweet'), ('sour', 'Sour'), ('sweer and sour', 'Sweet and Sour'), ('dry', 'Dry'), ('bitter', 'Bitter'), ('strong', 'Strong'), ('sparkling', 'Sparkling'), ('creamy', 'Creamy'), ('fruity', 'Fruity'), ('spicy', 'Spicy'), ('hot', 'Hot'), ('other', 'Other')], max_length=50),
        ),
    ]
