# Generated by Django 5.1.7 on 2025-03-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0008_alter_cocktail_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='category',
            field=models.CharField(choices=[('soft drink', 'Soft Drink'), ('sweet', 'Sweet'), ('sour', 'Sour'), ('sweet and sour', 'Sweet and Sour'), ('dry', 'Dry'), ('bitter', 'Bitter'), ('strong', 'Strong'), ('sparkling', 'Sparkling'), ('creamy', 'Creamy'), ('fruity', 'Fruity'), ('spicy', 'Spicy'), ('hot', 'Hot'), ('other', 'Other')], max_length=50),
        ),
    ]
