# Generated by Django 5.1.7 on 2025-03-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0010_remove_cocktail_cocktail_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
