# Generated by Django 5.1.7 on 2025-03-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0011_ingredient_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='alcoholic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cocktailingredient',
            name='unit',
            field=models.CharField(choices=[('ml', 'ml'), ('cl', 'cl'), ('g', 'g'), ('oz', 'oz'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('dash', 'dash'), ('piece', 'piece'), ('slice', 'slice'), ('wedge', 'wedge'), ('leaf', 'leaf'), ('pinch', 'pinch'), ('drop', 'drop'), ('cup', 'cup'), ('shot', 'shot'), ('bottle', 'bottle'), ('can', 'can'), ('bunch', 'bunch'), ('bottle', 'bottle'), ('other', 'other')], default='ml', max_length=50),
        ),
    ]
